baseURL = "https://longx.bio/"
# title = "LongX"

paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "hugo-paper"
title = "LongX"

[params]
  color = 'linen'

  avatar = 'hi@longx.bio'
  name = 'LongX'
  bio = 'Homebase for all Longevity Xplorers'
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 10
  [[menu.main]]
    identifier = "connect"
    name = "Connect"
    url = "/connect/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"




[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
